stages:
  - validate
  - plan 
  - apply 
  - destroy

.base:
  image: 
    name: hashicorp/terraform
    entrypoint: [""]
  before_script:
    - terraform init

validate:
  extends: .base
  stage: validate
  script: 
    - terraform validate

plan: 
  extends: .base
  stage: plan 
  script:
    - terraform plan -out=plan.out
  cache: 
    key: plan
    policy: push
    patchs: 
      - plan.out

apply:
  extends: .base
  stage: apply 
  script:
    - terraform apply plan.out
  cache:
    policy: pull
    patchs:
      - plan.out
  when: manual

destroy: 
  extends: .base
  stage: destroy
  script: 
    - terraform destroy -auto-approve
  when: manual
